// Fragrantica direct perfume-page URL map
// Auto-scraped via Algolia (fragrantica_perfumes index) + hand-verified overrides.
// Keys: normalize(brand) + "|" + normalize(name). Unmapped perfumes fall back to search.
(function () {
  var URLS = {
  "creed|aventus absolu": "https://www.fragrantica.com/perfume/Creed/Absolu-Aventus-106624.html",
  "versace|eros": "https://www.fragrantica.com/perfume/Versace/Eros-16657.html",
  "chanel|bleu de chanel": "https://www.fragrantica.com/perfume/Chanel/Bleu-de-Chanel-9099.html",
  "carolina herrera|bad boy": "https://www.fragrantica.com/perfume/Carolina-Herrera/Bad-Boy-55449.html",
  "gucci|guilty pour homme": "https://www.fragrantica.com/perfume/Gucci/Guilty-Pour-Homme-11037.html",
  "paco rabanne|invictus": "https://www.fragrantica.com/perfume/Rabanne/Invictus-18471.html",
  "dior|homme intense": "https://www.fragrantica.com/perfume/Dior/Dior-Homme-Intense-2011-13016.html",
  "dolce and gabbana|light blue": "https://www.fragrantica.com/perfume/Dolce-Gabbana/Light-Blue-485.html",
  "yves saint laurent|y eau de parfum": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html",
  "cartier|declaration d un soir": "https://www.fragrantica.com/perfume/Cartier/Declaration-d-Un-Soir-15462.html",
  "dolce and gabbana|k by dolce and gabbana": "https://www.fragrantica.com/perfume/Dolce-Gabbana/K-by-Dolce-Gabbana-56358.html",
  "parfums de marly|layton": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Layton-39314.html",
  "parfums de marly|haltane": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Haltane-70776.html",
  "hugo boss|boss elixir": "https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Bottled-Elixir-84074.html",
  "paco rabanne|1 million gold": "https://www.fragrantica.com/perfume/Rabanne/1-Million-Absolutely-Gold-15951.html",
  "dior|fahrenheit": "https://www.fragrantica.com/perfume/Dior/Fahrenheit-228.html",
  "calvin klein|ck one": "https://www.fragrantica.com/perfume/Calvin-Klein/CK-One-276.html",
  "tiziana terenzi|kirke": "https://www.fragrantica.com/perfume/Tiziana-Terenzi/Kirke-32172.html",
  "bdk parfums|velvet": "https://www.fragrantica.com/perfume/BDK-Parfums/Velvet-Tonka-68119.html",
  "mugler|a men fantasm": "https://www.fragrantica.com/perfume/Mugler/A-Men-Fantasm-93266.html",
  "yves saint laurent|tuxedo": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Tuxedo-32269.html",
  "paco rabanne|1 million royal": "https://www.fragrantica.com/perfume/Rabanne/1-Million-Royal-79159.html",
  "yves saint laurent|y elixir": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Elixir-90024.html",
  "hugo boss|boss intense": "https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Intense-388.html",
  "yves saint laurent|kouros": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Kouros-735.html",
  "paco rabanne|pure xs": "https://www.fragrantica.com/perfume/Rabanne/Pure-XS-46038.html",
  "paco rabanne|1 million elixir": "https://www.fragrantica.com/perfume/Rabanne/1-Million-Elixir-71708.html",
  "giorgio armani|stronger with you sandalwood": "https://www.fragrantica.com/perfume/Giorgio-Armani/Emporio-Armani-Stronger-With-You-Sandalwood-102519.html",
  "dolce and gabbana|pineapple": "https://www.fragrantica.com/perfume/Dolce-Gabbana/Pineapple-59231.html",
  "montblanc|legend": "https://www.fragrantica.com/perfume/Montblanc/Legend-11784.html",
  "azzaro|chrome": "https://www.fragrantica.com/perfume/Azzaro/Chrome-788.html",
  "louis vuitton|ombre nomade": "https://www.fragrantica.com/perfume/Louis-Vuitton/Ombre-Nomade-49755.html",
  "creed|silver mountain water": "https://www.fragrantica.com/perfume/Creed/Silver-Mountain-Water-472.html",
  "giorgio armani|stronger with you oud": "https://www.fragrantica.com/perfume/Giorgio-Armani/Emporio-Armani-Stronger-With-You-Oud-76171.html",
  "parfums de marly|delina exclusif": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-Exclusif-50370.html",
  "versace|vanille rouge": "https://www.fragrantica.com/perfume/Versace/Vanille-Rouge-57701.html",
  "initio|narcotic delight": "https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Narcotic-Delight-89368.html",
  "kajal|lamar": "https://www.fragrantica.com/perfume/Kajal/Lamar-62571.html",
  "diesel|diesel": "https://www.fragrantica.com/perfume/Diesel/Diesel-7542.html",
  "sospiro|opera": "https://www.fragrantica.com/perfume/Sospiro-Perfumes/Opera-26282.html",
  "creed|queen of silk": "https://www.fragrantica.com/perfume/Creed/Queen-of-Silk-89643.html",
  "tiziana terenzi|orza": "https://www.fragrantica.com/perfume/Tiziana-Terenzi/Orza-61873.html",
  "giorgio armani|noir kogane": "https://www.fragrantica.com/perfume/Giorgio-Armani/Noir-Kogane-88628.html",
  "dior|gris dior": "https://www.fragrantica.com/perfume/Dior/Gris-Dior-48387.html",
  "kajal|dahab": "https://www.fragrantica.com/perfume/Kajal/Dahab-32266.html",
  "parfums de marly|pegasus": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Pegasus-16938.html",
  "maison francis kurkdjian|baccarat rouge 540": "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html",
  "tom ford|black orchid": "https://www.fragrantica.com/perfume/Tom-Ford/Black-Orchid-1018.html",
  "creed|aventus": "https://www.fragrantica.com/perfume/Creed/Aventus-9828.html",
  "dior|sauvage": "https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html",
  "tom ford|tobacco vanille": "https://www.fragrantica.com/perfume/Tom-Ford/Tobacco-Vanille-1825.html",
  "tom ford|oud wood": "https://www.fragrantica.com/perfume/Tom-Ford/Oud-Wood-1826.html",
  "yves saint laurent|la nuit de l homme": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/La-Nuit-de-l-Homme-5521.html",
  "tom ford|lost cherry": "https://www.fragrantica.com/perfume/Tom-Ford/Lost-Cherry-51411.html",
  "giorgio armani|acqua di gio profumo": "https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gio-Profumo-29727.html",
  "jean paul gaultier|ultra male": "https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Ultra-Male-30947.html",
  "valentino|uomo born in roma": "https://www.fragrantica.com/perfume/Valentino/Valentino-Uomo-Born-in-Roma-55963.html",
  "viktor and rolf|spicebomb extreme": "https://www.fragrantica.com/perfume/Viktor-Rolf/Spicebomb-Extreme-30499.html",
  "montblanc|explorer": "https://www.fragrantica.com/perfume/Montblanc/Explorer-52002.html",
  "bvlgari|man in black": "https://www.fragrantica.com/perfume/Bvlgari/Bvlgari-Man-In-Black-26358.html",
  "chanel|allure homme sport": "https://www.fragrantica.com/perfume/Chanel/Allure-Homme-Sport-607.html",
  "tom ford|tuscan leather": "https://www.fragrantica.com/perfume/Tom-Ford/Tuscan-Leather-1849.html",
  "giorgio armani|armani code absolu": "https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-Absolu-53106.html",
  "hermes|terre d hermes": "https://www.fragrantica.com/perfume/Hermes/Terre-d-Hermes-17.html",
  "azzaro|the most wanted": "https://www.fragrantica.com/perfume/Azzaro/The-Most-Wanted-66826.html",
  "issey miyake|l eau d issey pour homme": "https://www.fragrantica.com/perfume/Issey-Miyake/L-Eau-d-Issey-Pour-Homme-721.html",
  "prada|luna rossa carbon": "https://www.fragrantica.com/perfume/Prada/Luna-Rossa-Carbon-Eau-de-Toilette-43402.html",
  "narciso rodriguez|for him bleu noir": "https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-Rodriguez-for-Him-Bleu-Noir-31247.html",
  "calvin klein|eternity for men": "https://www.fragrantica.com/perfume/Calvin-Klein/Eternity-For-Men-258.html",
  "valentino|born in roma donna": "https://www.fragrantica.com/perfume/Valentino/Valentino-Donna-Born-In-Roma-55805.html",
  "creed|green irish tweed": "https://www.fragrantica.com/perfume/Creed/Green-Irish-Tweed-474.html",
  "chanel|egoiste platinum": "https://www.fragrantica.com/perfume/Chanel/Egoiste-Platinum-614.html",
  "mugler|a men pure havane": "https://www.fragrantica.com/perfume/Mugler/A-Men-Pure-Havane-11444.html",
  "rasasi|la yuqawam": "https://www.fragrantica.com/perfume/Rasasi/La-Yuqawam-Homme-19668.html",
  "mancera|cedrat boise": "https://www.fragrantica.com/perfume/Mancera/Cedrat-Boise-15211.html",
  "amouage|reflection man": "https://www.fragrantica.com/perfume/Amouage/Reflection-Man-920.html",
  "parfums de marly|sedley": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Sedley-56273.html",
  "initio|side effect": "https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Side-Effect-42260.html",
  "maison francis kurkdjian|grand soir": "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Grand-Soir-40816.html",
  "paco rabanne|1 million night": "https://www.fragrantica.com/perfume/Rabanne/1-Million-Night-Elixir-125545.html",
  "kayali|freedom musk matcha": "https://www.fragrantica.com/perfume/Kayali-Fragrances/Freedom-Musk-Matcha-45-Eau-de-Parfum-118623.html",
  "xerjoff|torino21": "https://www.fragrantica.com/perfume/Xerjoff/Torino21-70424.html",
  "guerlain|aqua allegoria florabloom forte": "https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-Forte-89855.html",
  "mugler|angel nova": "https://www.fragrantica.com/perfume/Mugler/Angel-Nova-61519.html",
  "giorgio armani|acqua di gio elixir": "https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gio-Elixir-101438.html",
  "paco rabanne|fame in love": "https://www.fragrantica.com/perfume/Rabanne/Fame-in-Love-120952.html",
  "dolce and gabbana|l imperatrice 3": "https://www.fragrantica.com/perfume/Dolce-Gabbana/D-G-Anthology-L-Imperatrice-3-6086.html",
  "sisley|eau du soir": "https://www.fragrantica.com/perfume/Sisley/Eau-du-Soir-1002.html",
  "amouage|guidance 46": "https://www.fragrantica.com/perfume/Amouage/Guidance-46-94033.html",
  "kilian|her majesty": "https://www.fragrantica.com/perfume/By-Kilian/Her-Majesty-121840.html",
  "armani|si passione red musk": "https://www.fragrantica.com/perfume/Giorgio-Armani/Si-Passione-Red-Musk-103518.html",
  "narciso rodriguez|narciso bleu noir": "https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-Rodriguez-for-Him-Bleu-Noir-31247.html",
  "matiere premiere|vanilla powder": "https://www.fragrantica.com/perfume/Matiere-Premiere/Vanilla-Powder-84933.html",
  "armani|si passione intense": "https://www.fragrantica.com/perfume/Giorgio-Armani/Si-Passione-Intense-58737.html",
  "nautica|nautica voyage": "https://www.fragrantica.com/perfume/Nautica/Nautica-Voyage-913.html",
  "xerjoff|40 knots": "https://www.fragrantica.com/perfume/Xerjoff/40-Knots-16445.html",
  "valentino|valentina poudre": "https://www.fragrantica.com/perfume/Valentino/Valentina-Poudre-34936.html",
  "dior|rose star": "https://www.fragrantica.com/perfume/Dior/Rose-Star-106146.html",
  "tom ford|oud voyager": "https://www.fragrantica.com/perfume/Tom-Ford/Oud-Voyager-111206.html",
  "viktor and rolf|flowerbomb extreme": "https://www.fragrantica.com/perfume/Viktor-Rolf/Flowerbomb-Extreme-1462.html",
  "guerlain|santal royal": "https://www.fragrantica.com/perfume/Guerlain/Santal-Royal-96470.html",
  "orto parisi|terroni": "https://www.fragrantica.com/perfume/Orto-Parisi/Terroni-45475.html",
  "tom ford|noir extreme": "https://www.fragrantica.com/perfume/Tom-Ford/Noir-Extreme-29675.html",
  "rosendo mateu|rosendo mateu n 5": "https://www.fragrantica.com/perfume/Rosendo-Mateu-Olfactive-Expressions/Rosendo-Mateu-No-5-Elixir-99801.html",
  "azzaro|wanted elixir": "https://www.fragrantica.com/perfume/Azzaro/Forever-Wanted-Elixir-102882.html",
  "gisada|ambassador": "https://www.fragrantica.com/perfume/Gisada/Ambassador-Men-58226.html",
  "jo malone|myrrh and tonka": "https://www.fragrantica.com/perfume/Jo-Malone-London/Myrrh-Tonka-42027.html",
  "chanel|chanel n 5": "https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-Eau-de-Parfum-40069.html",
  "marc antoine barrois|ganymede": "https://www.fragrantica.com/perfume/Marc-Antoine-Barrois/Ganymede-54720.html",
  "armani|armani code parfum": "https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-Parfum-75126.html",
  "kayali|vanilla candy rock sugar": "https://www.fragrantica.com/perfume/Kayali-Fragrances/Vanilla-Candy-Rock-Sugar-42-92258.html",
  "kenzo|flower by kenzo": "https://www.fragrantica.com/perfume/Kenzo/Flower-by-Kenzo-72.html",
  "lancome|tresor la nuit": "https://www.fragrantica.com/perfume/Lancome/La-Nuit-Tresor-29157.html",
  "mugler|alien": "https://www.fragrantica.com/perfume/Mugler/Alien-707.html",
  "narciso rodriguez|narciso": "https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-26127.html",
  "ysl|black opium": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-25324.html",
  "ysl|mon paris": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Mon-Paris-38914.html",
  "yves saint laurent|libre edp": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-56077.html",
  "xerjoff|naxos": "https://www.fragrantica.com/perfume/Xerjoff/XJ-1861-Naxos-30529.html",
  "lattafa|assad elixir": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Asad-Elixir-117616.html",
  "parfums de marly|greenly": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Greenley-62101.html",
  "parfums de marly|valaya exclusive": "https://www.fragrantica.com/perfume/Parfums-de-Marly/Valaya-Exclusif-102806.html",
  "kayali|marshmallow": "https://www.fragrantica.com/perfume/Kayali-Fragrances/Yum-Boujee-Marshmallow-81-99254.html",
  "kayali|freedom musk": "https://www.fragrantica.com/perfume/Kayali-Fragrances/Freedom-Musk-Santal-34-Eau-de-Parfum-118622.html",
  "elie saab|elie saab in white": "https://www.fragrantica.com/perfume/Elie-Saab/Le-Parfum-in-White-48058.html",
  "givenchy|gentleman edp": "https://www.fragrantica.com/perfume/Givenchy/Gentleman-Eau-de-Parfum-48476.html",
  "burberry|hero edp": "https://www.fragrantica.com/perfume/Burberry/Hero-Eau-de-Parfum-75182.html",
  "maison margiela|by the fireplace": "https://www.fragrantica.com/perfume/Maison-Martin-Margiela/By-the-Fireplace-31623.html",
  "guerlain|l homme ideal edp": "https://www.fragrantica.com/perfume/Guerlain/L-Homme-Ideal-Eau-de-Parfum-37735.html"
};
  function norm(s) {
    return String(s || "")
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/&/g, " and ")
      .replace(/[^a-z0-9]+/g, " ")
      .trim();
  }
  window.FRAGRANTICA_URLS = URLS;
  window.fragranticaUrlFor = function (brand, name) {
    var hit = URLS[norm(brand) + "|" + norm(name)];
    if (hit) return hit;
    var q = [brand, name].filter(Boolean).join(" ").trim();
    return "https://www.fragrantica.com/search/?query=" + encodeURIComponent(q);
  };
})();
